return {
  "MeanderingProgrammer/render-markdown.nvim",
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons"
  },
  config = function()
    require("render-markdown").setup {
      heading = {
        enabled = true,
        sign = true,
        position = "overlay",
        icons = {
          "󰝤 ",
          "󰝤󰝤 ",
          "󰝤󰝤󰝤 ",
          "󰝤󰝤󰝤󰝤 ",
          "󰝤󰝤󰝤󰝤󰝤 ",
          "󰝤󰝤󰝤󰝤󰝤󰝤 ",
        },
        sign = false,
        width = "full",
        left_margin = 0,
        left_pad = 0,
        right_pad = 0,
        min_width = 0,
        border = false,
        border_virtual = false,
        border_prefix = false,
        above = "▄",
        below = "▀",
        backgrounds = {
          "RenderMarkdownH1",
          "RenderMarkdownH2",
          "RenderMarkdownH3",
          "RenderMarkdownH4",
          "RenderMarkdownH5",
          "RenderMarkdownH6",
        },
        foregrounds = {
          "RenderMarkdownH1",
          "RenderMarkdownH2",
          "RenderMarkdownH3",
          "RenderMarkdownH4",
          "RenderMarkdownH5",
          "RenderMarkdownH6",
        },
      },
      code = {
        enabled = true,
        sign = false,
        style = "normal",
        position = "left",
        language_name = false,
        border = "thick",
        above = "▄",
        below = "▀",
        highlight = "RenderMarkdownCode",
        highlight_inline = "RenderMarkdownCodeInline",
        highlight_language = nil,
        width = "block",
        min_width = 80,
      },
      dash = {
        enabled = true,
        icon = "─",
        width = 79,
        highlight = "EndOfBuffer",
      },
      bullet = {
        enabled = true,
        icons = { "•", "⚬" },
        ordered_icons = {},
        left_pad = 0,
        right_pad = 0,
        highlight = "RenderMarkdownBullet",
      },
      checkbox = {
        unchecked = { icon = "󰄱 ", highlight="WhichKeyGroup" },
        checked =   { icon = "󰄲 ", highlight="MiniPickMatchRanges", scope_highlight = "@markup.strikethrough" },
        custom = {
          todo = { raw = "[-]", rendered = " ", highlight = "CursorLineFold", scope_highlight = "Comment"},
          question = { raw = "[?]", rendered = " ", highlight = "VimwikiHeader5" },
          bang = { raw = "[!]", rendered = "󰀦 ", highlight = "NvimInvalid" },
          info = { raw = "[i]", rendered = " ", highlight = "WarningMsg" },
          waiting = { raw = "[w]", rendered = " ", highlight = "WarningMsg" },
        },
      },
      quote = { enabled = false },
    }
  end,
}
